LINKTA-309: CD/Configure firebase hosting
Linkta-org/LandingPage pull request #34
Opened 2024-04-17 21:59 UTC by ChTiSh

## Description
Configured Firebase hosting for waiting list page.
Integration with Next will need to be configured as well.
This is a breaking change, putting PR as draft first so everyone is aware.

Fixes # (issue) LINKTA-309

## Type of change

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 Documentation update
- [X] Other 🗒️ CD

## How Has This Been Tested?

Test will be performed after Nextjs integration

## Checklist:

- [X] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have reviewed the [**Security Best Practices Document**](SECURITY_BEST_PRACTICES.md).
- [X] I have followed the [**Naming Conventions Guide**](NAMING_CONVENTIONS_GUIDE.md) for my changes.
- [X] I have ensured that my pull request title is descriptive.

## Additional Information:

2024-04-22 17:14 UTC, dcpavel requested changes, later dismissed
I'm a little confused if this is only the CD and configuring firebase hosting.

2024-04-22 17:14 UTC, dcpavel commented on public/404.html
Why is the error page within this PR? Also, the styling isn't consistent with the rest of the styling (not using tailwind). Is this part of firebase?

2024-04-22 17:14 UTC, dcpavel commented on public/index.html
Same as the 404 page, styling is inconsistent with the rest of the waiting list site. Is this part of firebase?

2024-04-24 06:28 UTC, ChTiSh commented on public/404.html
Yeah, auto generated by firebase, just removed.

2024-04-24 06:29 UTC, ChTiSh commented on public/index.html
Same as 404, auto-generated by firebase, also removed

2024-04-24 22:21 UTC, kinskiwu approved these changes

2024-04-25 00:58 UTC, colinvandergraaf approved these changes
This looks good.  Looking forward to testing this more thoroughly once we have it all integrated. BTW, I watched an earlier version of this video about  [ default settings in firebase configurations let to easily hackable apps](https://www.youtube.com/watch?v=TKyNPg7UIIc) because proper security rules aren't implemented by default.

2024-04-25 04:45 UTC, zhiyi15 approved these changes

2024-04-25 05:01 UTC, merged