LINKTA-341 style error and notfound pages
Linkta-org/LandingPage pull request #51
Opened 2024-04-27 05:42 UTC by lomeintheory

## Description

Fixes # (issue)

## Type of change

- [ ] ✨ New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

ran on localhost

## Checklist:

- [ ] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have reviewed the [**Security Best Practices Document**](SECURITY_BEST_PRACTICES.md).
- [ ] I have followed the [**Naming Conventions Guide**](NAMING_CONVENTIONS_GUIDE.md) for my changes.
- [ ] I have ensured that my pull request title is descriptive.

## Additional Information:

- Any remaining styling will be handled by @ChTiSh

2024-04-29 21:49 UTC, kinskiwu requested changes, later dismissed
Please make the following changes:
- Revert the not-found content to its original
- Add lottie animation to both not-found and error.tsx according to the appropriate color pallette discussed
- Convert the styling inside 'Player' to tailwind to be consistent with the rest of the landing page 
- Add accessibility attributes to the lottie animation

Note: The `Control` component may be unnecessary for these pages. Please refer to the doc to confirm. If confirmed unnecessary pls also remove the related code. Thank you!

2024-04-30 15:20 UTC, kinskiwu commented on app/not-found.tsx
> +    <div>
`Page Not Found` and `We couldn't find the page you're looking for' seems duplicated. Maybe remove one of them?

2024-04-30 15:40 UTC, kinskiwu commented on app/not-found.tsx
> +      </div>
Maybe move `click` outside of the hyperlink text to clarify `here` is the word to interact with for navigation?
```
<p className="mb-64 text-light-text">Please click<a href="/" className="text-light-text underline hover:via-light-hover">here</a> to return home or contact us at <a href="mailto:info@linkta.org">info@linkta.org</a></p>
```

2024-04-30 15:45 UTC, kinskiwu commented on app/error.tsx
> +      <p className="mb-48">
Maybe move `click` outside of the hyperlink text to clarify `here` is the word to interact with for navigation?

Also we can add some styling, such as bold text, change color when hover, and add an underline for email etc. to make the `here` and `email` stand out so the user is clear where to click.

```
      <p className="mb-48">
        Please click<a href="#" onClick={() => reset()}className="font-bold hover:text-red-500"> here</a> to refresh the page or contact us at <a href="mailto:info@linkta.org" className="underline hover:text-red-500">info@linkta.org</a>
      </p>
```

2024-04-30 16:02 UTC, kinskiwu commented on app/error.tsx
At the moment the animation is a bit off-centered. We can add some basic styling to align the components (I also adjusted the size of the animation from 350px to 150px for the visuals):

```
    <div className="flex flex-col items-center justify-center">
      <h2 className="mt-12 text-3xl text-left font-semibold">Oops!</h2>
      <p className="mt-4 text-left">Something went wrong!</p>
      <div className="flex justify-center items-center mt-12 mb-12" aria-label='Error page' aria-live='assertive'>
        <Player
        autoplay={true}
        loop={true}
        className="w-[150px] h-[150px]"
        src={ErrorAnimation}
        >
        </Player>
      </div>
      <p className="mb-48">
        Please click<a href="#" onClick={() => reset()}className="font-bold hover:text-red-500"> here</a> to refresh the page or contact us at <a href="mailto:info@linkta.org" className="underline hover:text-red-500">info@linkta.org</a>
      </p>
    </div>
```

![image](https://github.com/Linkta-org/landing-page/assets/112212841/19718b9e-8e63-4773-8deb-f321af94623c)

2024-04-30 16:03 UTC, kinskiwu commented on app/not-found.tsx
> +    <div>
Also the same comment about centering the animation.

2024-05-01 00:26 UTC, kinskiwu reviewed
I'm gonna remove this block for now in case we need to merge this PR tonight.

2024-05-01 07:30 UTC, lomeintheory commented
@kinskiwu Just made the requested changes and ran on localhost to test how the components look. Let me know if I'm missing anything, thank you!

2024-05-01 13:41 UTC, kinskiwu approved these changes
Thanks for the good work!

2024-05-01 22:13 UTC, ejwoods approved these changes
Styling looks good 👍

2024-05-02 00:19 UTC, merged